version: '2'
services:
  test:
    build: .
    image: template-to-pdf
    command: npm test
    volumes:
    - ./package.json:/var/task/package.json
    - ./test:/var/task/test
    - ./index.js:/var/task/index.js
    - ./styles.css:/var/task/styles.css
    - ./scripts.js:/var/task/scripts.js
    - ./test/tmp:/tmp
    - ./fontconfig:/var/task/fontconfig
  
  package:
    build: .
    image: template-to-pdf
    command: npm run package
    volumes:
    - ./output:/var/task/output
    - ./index.js:/var/task/index.js