version: '2'
services:
  start:
    build: .
    image: template-to-pdf
    command: /bin/bash
    ports:
    - "9231:9231"
    volumes:
    - ./test:/home/test
    - ./index.js:/home/index.js
    - ./utils.js:/home/utils.js
    - ./styles.css:/home/styles.css
    - ./scripts.js:/home/scripts.js
    - ./package.json:/home/package.json
    mem_limit: 1028m
    restart: always