version: '2'
services:
  start:
    build: .
    image: template-to-pdf
    command: npm start
    ports:
    - "80:80"
    mem_limit: 1028m
    restart: always

  test:
    build: .
    image: template-to-pdf
    command: npm test
    volumes:
    - ./package.json:/var/task/package.json
    - ./test:/var/task/test
    - ./index.js:/var/task/index.js
    - ./styles.css:/var/task/styles.css
    - ./scripts.js:/var/task/scripts.js
    - ./test/tmp:/tmp
    - ./fontconfig:/var/task/fontconfig